### ISSUE TITLE
The link of preprocessed csv file is not available

### ISSUE THREAD

**Issue by hungrydonkey** [Aida-yy/multi-stage-attack-detection#1]
The [link](https://drive.google.com/file/d/1uYQF-sNEuWcvzyCzrE1HBRJsXKknN432/view?usp=sharing) shows that "Sorry, the file you have requested does not exist."

Can you provide a new file sharing link?

**Comment by kylin-zhou** [comment]
@hungrydonkey  The new file link has be updated.

**Comment by hungrydonkey** [comment]
Thank you. I closed the issue.
